export const ADD_VIDEOS = 'ADD_VIDEOS';
export const REMOVE_VIDEO = 'REMOVE_VIDEO';
export const REMOVE_ALL_VIDEOS = 'REMOVE_ALL_VIDEOS';
export const VIDEO_PROGRESS = 'VIDEO_PROGRESS';
export const VIDEO_COMPLETE = 'VIDEO_COMPLETE';
export const SET_FORMAT = 'SET_FORMAT';
